# Generated by Django 2.2.5 on 2019-09-29 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author_name', models.CharField(max_length=40)),
                ('author_id', models.CharField(max_length=40)),
                ('creation_date', models.CharField(max_length=40)),
                ('file_location', models.CharField(max_length=200)),
            ],
        ),
    ]
