# Generated by Django 2.2.5 on 2019-09-29 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='file_location',
            new_name='file_id',
        ),
    ]
