# Generated by Django 2.2.6 on 2019-10-18 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20190929_0003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='posts',
            name='file_id',
            field=models.FileField(upload_to='posts'),
        ),
    ]
