# Generated by Django 2.2.6 on 2019-10-18 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20191017_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='file_id',
            field=models.FileField(max_length=200, upload_to='posts'),
        ),
    ]
