# Generated by Django 2.2.6 on 2019-10-19 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_auto_20191017_2336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custom_user',
            name='posts_ids',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
