# Generated by Django 2.2.6 on 2019-10-19 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_auto_20191018_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custom_user',
            name='posts_ids',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
