# Generated by Django 2.2.6 on 2019-10-19 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_auto_20191018_2243'),
    ]

    operations = [
        migrations.AddField(
            model_name='custom_user',
            name='custom_username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
